/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PriorityService } from "../priority.service";
import { PriorityCreateInput } from "./PriorityCreateInput";
import { Priority } from "./Priority";
import { PriorityFindManyArgs } from "./PriorityFindManyArgs";
import { PriorityWhereUniqueInput } from "./PriorityWhereUniqueInput";
import { PriorityUpdateInput } from "./PriorityUpdateInput";
import { TicketFindManyArgs } from "../../ticket/base/TicketFindManyArgs";
import { Ticket } from "../../ticket/base/Ticket";
import { TicketWhereUniqueInput } from "../../ticket/base/TicketWhereUniqueInput";

export class PriorityControllerBase {
  constructor(protected readonly service: PriorityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Priority })
  async createPriority(
    @common.Body() data: PriorityCreateInput
  ): Promise<Priority> {
    return await this.service.createPriority({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Priority] })
  @ApiNestedQuery(PriorityFindManyArgs)
  async priorities(@common.Req() request: Request): Promise<Priority[]> {
    const args = plainToClass(PriorityFindManyArgs, request.query);
    return this.service.priorities({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Priority })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async priority(
    @common.Param() params: PriorityWhereUniqueInput
  ): Promise<Priority | null> {
    const result = await this.service.priority({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Priority })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePriority(
    @common.Param() params: PriorityWhereUniqueInput,
    @common.Body() data: PriorityUpdateInput
  ): Promise<Priority | null> {
    try {
      return await this.service.updatePriority({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Priority })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePriority(
    @common.Param() params: PriorityWhereUniqueInput
  ): Promise<Priority | null> {
    try {
      return await this.service.deletePriority({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tickets")
  @ApiNestedQuery(TicketFindManyArgs)
  async findTickets(
    @common.Req() request: Request,
    @common.Param() params: PriorityWhereUniqueInput
  ): Promise<Ticket[]> {
    const query = plainToClass(TicketFindManyArgs, request.query);
    const results = await this.service.findTickets(params.id, {
      ...query,
      select: {
        assigned: true,

        comment: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        createdDate: true,
        id: true,

        priority: {
          select: {
            id: true,
          },
        },

        program: true,
        resource: true,
        state: true,
        subject: true,
        ticketNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tickets")
  async connectTickets(
    @common.Param() params: PriorityWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        connect: body,
      },
    };
    await this.service.updatePriority({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tickets")
  async updateTickets(
    @common.Param() params: PriorityWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        set: body,
      },
    };
    await this.service.updatePriority({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tickets")
  async disconnectTickets(
    @common.Param() params: PriorityWhereUniqueInput,
    @common.Body() body: TicketWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tickets: {
        disconnect: body,
      },
    };
    await this.service.updatePriority({
      where: params,
      data,
      select: { id: true },
    });
  }
}
